import Head from "next/head";
function CustomHead() {
  return (
    <>
      <Head>
        <title>Vahak Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
export default CustomHead;
